---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: flux-system
spec:
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 7.4.0
  values:
    replicaCount: 2
  interval: 1m
  releaseName: apache-test
  targetNamespace: default

