---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: flux-system
spec:
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 7.4.0
  install:
    disableWait: true
  upgrade:
    disableWait: true
#  install:
#    timeout: 5m
  values:
    replicaCount: 3
  interval: 5m
  releaseName: apache-test
  targetNamespace: default

