---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 9.1.0
  values:
    replicaCount: 2
    service:
      type: ClusterIP
    cloneStaticSiteFromGit:
      enabled: true
      repository: https://github.com/ithinkihaveacat/hello-world-html
      branch: master
  interval: 1m
  releaseName: nginx-test
  targetNamespace: default

