---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 9.1.0
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3          
#    disableWait: true
#  upgrade:
#    disableWait: true
#  install:
#    timeout: 5m
  values:
    replicaCount: 2
  interval: 1m
  releaseName: nginx-test
  targetNamespace: default

