---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 7.6.9
  interval: 1h0m0s
  releaseName: nginx-ingress-controller
  targetNamespace: kube-system

